# Training and Evaluation in one Notebook for One Model-Database Pair

# To check before running
1. Check class names for your event log in the **p2pencoder.py** ( *{event_log_name}encoder.py* )
2. Check the Axioms in **axiombuilder.py**
3. make sure you have done the declare mining on the event log and have a valid **ltn_rows_path**

In [41]:
event_log_name = "wide"
if event_log_name is None:
    raise ValueError("Please set the event_log_name variable to the name of the event log you want to use.")
ltn_rows_path = f"{event_log_name}_ltn_rows.pkl"
print(f"Event log name {event_log_name}")
print(f"LTN Rows path {ltn_rows_path}")
# starting time

Event log name wide
LTN Rows path wide_ltn_rows.pkl

In [42]:
# import tensorflow as tf
# physical_devices = tf.config.list_physical_devices('GPU')
# print(physical_devices)
# if len(physical_devices) > 0:
#     tf.config.experimental.set_memory_growth(physical_devices[0], True)
#     print("GPU found")
#     print("Memory growth set")
# else:
#     print("No GPU found")

In [43]:
import arrow
import socket
from sqlalchemy.orm import Session
from tqdm.notebook import tqdm

from april.anomalydetection import *
from april.database import EventLog
from april.database import Model
from april.database import get_engine
from april.dataset import Dataset
from april.fs import DATE_FORMAT
from april.fs import get_event_log_files

import itertools

from sklearn import metrics


from april.anomalydetection import BINet
from april.anomalydetection.utils import label_collapse
from april.database import Evaluation
from april.wideevaluator import Evaluator
from april.fs import get_model_files
from april.fs import PLOT_DIR

import matplotlib.pyplot as plt
import numpy as np
np.random.seed(0)

import pandas as pd
import seaborn as sns
from sqlalchemy.orm import Session
import scikit_posthocs as sp

from april.database import get_engine
from april.fs import PLOT_DIR
from april.utils import microsoft_colors, prettify_dataframe, cd_plot, get_cd
from april.enums import Base, Strategy, Heuristic

sns.set_style('white')
pd.set_option('display.max_rows', 50)
%config InlineBackend.figure_format = 'retina'
print(wide_leaky_row_classes)

[<class 'april.anomalydetection.wideencoder.WideDAE-Leaky-10'>, <class 'april.anomalydetection.wideencoder.WideDAE-Leaky-25'>, <class 'april.anomalydetection.wideencoder.WideDAE-Leaky-50'>, <class 'april.anomalydetection.wideencoder.WideDAE-Leaky-100'>, <class 'april.anomalydetection.wideencoder.WideDAE-Leaky-150'>, <class 'april.anomalydetection.wideencoder.WideDAE-Leaky-200'>, <class 'april.anomalydetection.wideencoder.WideDAE-Leaky-250'>, <class 'april.anomalydetection.wideencoder.WideDAE-Leaky-300'>]

In [44]:
dataset = f"{event_log_name}-0.3-1"
out_dir = PLOT_DIR / f'{event_log_name}_evaluations_both_{arrow.now().format("YYYY-MM-DD-HH-mm-ss")}'
eval_file = out_dir / f'{event_log_name}_fraction_evaluations.pkl'
csv_file = out_dir / f'{event_log_name}_fraction_evaluations.csv'
excel_file = out_dir / f'{event_log_name}_fraction_evaluations.xlsx'
model_folder = r"D:\LTNcoder\.out\models"
db = r"D:\LTNcoder\.out\april.db"

# create out_dir if it does not exist
if not out_dir.exists():
    out_dir.mkdir(parents=True, exist_ok=True)
    print(f"Created directory: {out_dir}")
from april.utils import delete_all_files_in_folder, delete_evaluation_and_model_tables
delete_all_files_in_folder(model_folder)
delete_evaluation_and_model_tables(db)
start_time = arrow.now("Europe/Berlin")

Created directory: d:\LTNcoder\.out\plots\wide_evaluations_both_2025-08-17-18-38-10
Deleted all rows from Evaluation and Model tables.

# Training

In [45]:
def fit_and_save(dataset_name, ad, ad_kwargs=None, fit_kwargs=None):
    if ad_kwargs is None:
        ad_kwargs = {}
    if fit_kwargs is None:
        fit_kwargs = {}

    # Save start time
    start_time = arrow.now()

    # Dataset
    dataset = Dataset(dataset_name)

    # AD
    ad = ad(**ad_kwargs)

    # Train and save
    ad.fit(dataset, **fit_kwargs)
    file_name = f'{dataset_name}_{ad.abbreviation}_{start_time.format(DATE_FORMAT)}'
    model_file = ad.save(file_name)

    # Save end time
    end_time = arrow.now()

    # Cache result
    Evaluator(model_file.str_path).cache_result()

    # Calculate training time in seconds
    training_time = (end_time - start_time).total_seconds()

    # Write to database
    engine = get_engine()
    session = Session(engine)

    session.add(Model(creation_date=end_time.datetime,
                      algorithm=ad.name,
                      training_duration=training_time,
                      file_name=model_file.file,
                      training_event_log_id=EventLog.get_id_by_name(dataset_name),
                      training_host=socket.gethostname(),
                      hyperparameters=str(dict(**ad_kwargs, **fit_kwargs))))
    session.commit()
    session.close()

    if isinstance(ad, NNAnomalyDetector):
        from keras.backend import clear_session
        clear_session()
    pass

In [46]:
ads = [
        dict(ad=WideDAE, fit_kwargs=dict(epochs=6, batch_size=100)),
    ] + \
    [
        dict(ad=LEAKY_ROW_CLASS, fit_kwargs=dict(epochs=6, batch_size=100)) for LEAKY_ROW_CLASS 
        in wide_leaky_row_classes
    ] + \
    [
        dict(ad=LTN_ROW_CLASS, fit_kwargs=dict(epochs=6, batch_size=100, epochs_ltn=3))
        for LTN_ROW_CLASS in wide_ltn_row_classes
    ]
print(ads)
for ad in tqdm(ads, desc="Fitting ADs"):
    fit_and_save(dataset, **ad)

[{'ad': <class 'april.anomalydetection.wideencoder.WideDAE'>, 'fit_kwargs': {'epochs': 6, 'batch_size': 100}}, {'ad': <class 'april.anomalydetection.wideencoder.WideDAE-Leaky-10'>, 'fit_kwargs': {'epochs': 6, 'batch_size': 100}}, {'ad': <class 'april.anomalydetection.wideencoder.WideDAE-Leaky-25'>, 'fit_kwargs': {'epochs': 6, 'batch_size': 100}}, {'ad': <class 'april.anomalydetection.wideencoder.WideDAE-Leaky-50'>, 'fit_kwargs': {'epochs': 6, 'batch_size': 100}}, {'ad': <class 'april.anomalydetection.wideencoder.WideDAE-Leaky-100'>, 'fit_kwargs': {'epochs': 6, 'batch_size': 100}}, {'ad': <class 'april.anomalydetection.wideencoder.WideDAE-Leaky-150'>, 'fit_kwargs': {'epochs': 6, 'batch_size': 100}}, {'ad': <class 'april.anomalydetection.wideencoder.WideDAE-Leaky-200'>, 'fit_kwargs': {'epochs': 6, 'batch_size': 100}}, {'ad': <class 'april.anomalydetection.wideencoder.WideDAE-Leaky-250'>, 'fit_kwargs': {'epochs': 6, 'batch_size': 100}}, {'ad': <class 'april.anomalydetection.wideencoder.WideDAE-Leaky-300'>, 'fit_kwargs': {'epochs': 6, 'batch_size': 100}}, {'ad': <class 'april.anomalydetection.wideencoder.WideLTNFROZEN-10'>, 'fit_kwargs': {'epochs': 6, 'batch_size': 100, 'epochs_ltn': 3}}, {'ad': <class 'april.anomalydetection.wideencoder.WideLTNFROZEN-25'>, 'fit_kwargs': {'epochs': 6, 'batch_size': 100, 'epochs_ltn': 3}}, {'ad': <class 'april.anomalydetection.wideencoder.WideLTNFROZEN-50'>, 'fit_kwargs': {'epochs': 6, 'batch_size': 100, 'epochs_ltn': 3}}, {'ad': <class 'april.anomalydetection.wideencoder.WideLTNFROZEN-100'>, 'fit_kwargs': {'epochs': 6, 'batch_size': 100, 'epochs_ltn': 3}}, {'ad': <class 'april.anomalydetection.wideencoder.WideLTNFROZEN-150'>, 'fit_kwargs': {'epochs': 6, 'batch_size': 100, 'epochs_ltn': 3}}, {'ad': <class 'april.anomalydetection.wideencoder.WideLTNFROZEN-200'>, 'fit_kwargs': {'epochs': 6, 'batch_size': 100, 'epochs_ltn': 3}}, {'ad': <class 'april.anomalydetection.wideencoder.WideLTNFROZEN-250'>, 'fit_kwargs': {'epochs': 6, 'batch_size': 100, 'epochs_ltn': 3}}, {'ad': <class 'april.anomalydetection.wideencoder.WideLTNFROZEN-300'>, 'fit_kwargs': {'epochs': 6, 'batch_size': 100, 'epochs_ltn': 3}}]

Fitting ADs:   0%|          | 0/17 [00:00<?, ?it/s]

Epoch 1/6
40/40 [==============================] - 1s 14ms/step - loss: 0.2234 - accuracy: 0.0433 - val_loss: 0.1588 - val_accuracy: 0.0000e+00
Epoch 2/6
40/40 [==============================] - 0s 6ms/step - loss: 0.0455 - accuracy: 0.1625 - val_loss: 0.0048 - val_accuracy: 0.0000e+00
Epoch 3/6
40/40 [==============================] - 0s 6ms/step - loss: 0.0047 - accuracy: 0.2453 - val_loss: 0.0044 - val_accuracy: 0.0000e+00
Epoch 4/6
40/40 [==============================] - 0s 6ms/step - loss: 0.0045 - accuracy: 0.2756 - val_loss: 0.0044 - val_accuracy: 0.0000e+00
Epoch 5/6
40/40 [==============================] - 0s 6ms/step - loss: 0.0044 - accuracy: 0.2858 - val_loss: 0.0043 - val_accuracy: 0.0000e+00
Epoch 6/6
40/40 [==============================] - 0s 7ms/step - loss: 0.0044 - accuracy: 0.3047 - val_loss: 0.0043 - val_accuracy: 0.0000e+00
d:\LTNcoder\.out\models\wide-0.3-1_widedae_20250817-183810.336025.keras
Loading model wide-0.3-1_widedae_20250817-183810.336025 / <april.fs.ModelFile object at 0x0000028772978C10> for event log wide-0.3-1 at path d:\LTNcoder\.out\models\wide-0.3-1_widedae_20250817-183810.336025.keras
Self.ad_: <april.anomalydetection.wideencoder.WideDAE object at 0x00000287720B6A00>
Filtering dataset to 610 LTN rows.
Indices: [21, 38, 39, 60, 64, 95, 108, 117, 119, 134, 141, 142, 143, 149, 155, 156, 174, 185, 215, 237, 244, 255, 257, 262, 267, 268, 277, 295, 299, 307, 323, 324, 336, 359, 361, 364, 370, 377, 380, 389, 390, 393, 404, 417, 421, 425, 434, 445, 451, 460, 469, 475, 477, 480, 488, 492, 498, 499, 502, 510, 526, 545, 546, 549, 573, 575, 584, 587, 595, 608, 612, 616, 628, 630, 632, 640, 643, 652, 653, 656, 672, 673, 682, 694, 705, 712, 715, 733, 742, 744, 764, 766, 768, 772, 773, 776, 777, 784, 800, 807, 808, 820, 826, 829, 830, 851, 865, 866, 887, 891, 899, 900, 905, 906, 928, 931, 953, 962, 965, 967, 970, 979, 980, 990, 993, 1027, 1034, 1044, 1045, 1047, 1055, 1058, 1068, 1072, 1081, 1098, 1121, 1123, 1144, 1151, 1170, 1174, 1181, 1182, 1188, 1209, 1216, 1222, 1226, 1227, 1238, 1244, 1249, 1250, 1253, 1254, 1265, 1270, 1278, 1282, 1326, 1328, 1335, 1340, 1347, 1355, 1381, 1395, 1416, 1418, 1437, 1438, 1440, 1446, 1448, 1458, 1463, 1469, 1492, 1493, 1496, 1518, 1529, 1536, 1544, 1556, 1561, 1563, 1564, 1571, 1578, 1588, 1594, 1598, 1602, 1603, 1631, 1640, 1653, 1654, 1655, 1674, 1675, 1676, 1684, 1691, 1698, 1699, 1701, 1714, 1715, 1717, 1723, 1729, 1739, 1742, 1744, 1749, 1753, 1758, 1765, 1768, 1773, 1779, 1781, 1782, 1784, 1790, 1796, 1814, 1817, 1848, 1858, 1859, 1876, 1902, 1905, 1906, 1907, 1933, 1973, 1976, 1993, 1996, 2003, 2005, 2008, 2011, 2021, 2022, 2053, 2054, 2057, 2071, 2077, 2083, 2084, 2095, 2100, 2113, 2114, 2118, 2130, 2131, 2133, 2135, 2148, 2152, 2167, 2170, 2178, 2179, 2187, 2188, 2192, 2201, 2205, 2206, 2213, 2214, 2217, 2222, 2238, 2243, 2244, 2252, 2253, 2281, 2291, 2295, 2302, 2303, 2310, 2321, 2322, 2323, 2343, 2348, 2349, 2351, 2356, 2370, 2393, 2402, 2409, 2410, 2412, 2416, 2420, 2449, 2461, 2468, 2491, 2502, 2506, 2519, 2520, 2521, 2526, 2536, 2539, 2541, 2545, 2548, 2552, 2558, 2571, 2574, 2575, 2576, 2582, 2586, 2587, 2592, 2606, 2609, 2615, 2638, 2650, 2654, 2658, 2661, 2666, 2667, 2677, 2679, 2682, 2686, 2708, 2711, 2719, 2723, 2735, 2742, 2746, 2752, 2763, 2781, 2788, 2792, 2797, 2798, 2800, 2823, 2825, 2826, 2836, 2844, 2846, 2852, 2859, 2864, 2879, 2882, 2891, 2899, 2905, 2908, 2912, 2922, 2925, 2928, 2930, 2933, 2934, 2944, 2975, 2976, 2982, 2987, 2995, 2996, 2998, 3004, 3012, 3070, 3071, 3079, 3085, 3088, 3100, 3109, 3120, 3124, 3126, 3147, 3150, 3164, 3173, 3174, 3181, 3188, 3198, 3210, 3218, 3221, 3231, 3233, 3237, 3251, 3280, 3293, 3302, 3304, 3308, 3316, 3323, 3325, 3341, 3346, 3348, 3357, 3358, 3372, 3377, 3378, 3381, 3384, 3385, 3391, 3396, 3402, 3404, 3477, 3485, 3486, 3492, 3494, 3511, 3519, 3526, 3538, 3554, 3555, 3568, 3579, 3588, 3595, 3598, 3612, 3622, 3623, 3625, 3632, 3680, 3683, 3688, 3694, 3701, 3713, 3715, 3722, 3726, 3763, 3799, 3800, 3805, 3810, 3827, 3837, 3841, 3848, 3853, 3875, 3891, 3914, 3924, 3928, 3941, 3944, 3950, 3976, 3979, 3989, 3995, 4002, 4008, 4033, 4063, 4085, 4090, 4092, 4106, 4114, 4116, 4120, 4131, 4132, 4142, 4148, 4175, 4179, 4181, 4184, 4188, 4192, 4223, 4237, 4251, 4254, 4260, 4262, 4276, 4291, 4303, 4328, 4339, 4342, 4351, 4382, 4390, 4399, 4409, 4418, 4424, 4428, 4433, 4441, 4443, 4454, 4479, 4488, 4495, 4502, 4505, 4508, 4526, 4532, 4540, 4541, 4562, 4565, 4566, 4583, 4587, 4594, 4603, 4609, 4615, 4618, 4623, 4627, 4637, 4645, 4647, 4659, 4668, 4671, 4674, 4689, 4711, 4725, 4726, 4729, 4735, 4743, 4752, 4755, 4757, 4765, 4776, 4790, 4792, 4795, 4800, 4808, 4810, 4811, 4812, 4813, 4822, 4828, 4833, 4837, 4864, 4885, 4892, 4893, 4894, 4903, 4913, 4932, 4936, 4948, 4956, 4963, 4983, 4991, 4996, 4998]
Evaluation dataset shape: (610, 12, 2)
20/20 [==============================] - 0s 1ms/step
wide-0.3-1 [ 58. 141.]
wide-0.3-1 [ 58. 141.]
wide-0.3-1 [ 58. 141.]
wide-0.3-1 [ 58. 141.]
Anomaly detection result for wide-0.3-1_widedae_20250817-183810.336025 on wide-0.3-1 with widedae saved to d:\LTNcoder\.out\.cache\results\wide-0.3-1_widedae_20250817-183810.336025.result
self._result: <april.anomalydetection.utils.result.AnomalyDetectionResult object at 0x00000287E5009B20>
self.result.scores: [[[3.83702400e-06 4.22886933e-06]
  [1.45163476e-05 3.87751003e-04]
  [5.06650322e-05 5.83975995e-03]
  ...
  [4.88977503e-06 4.17189358e-06]
  [3.99625242e-06 3.85529302e-06]
  [4.15184650e-06 4.22935318e-06]]

 [[3.10098471e-06 3.41526811e-06]
  [1.24967000e-05 3.66547436e-04]
  [5.07228251e-05 5.84406825e-03]
  ...
  [3.95855204e-06 3.33444768e-06]
  [3.25509359e-06 3.12301222e-06]
  [3.31871752e-06 3.41039822e-06]]

 [[1.06698808e-05 1.15557332e-05]
  [3.31122838e-02 1.13794906e-02]
  [3.20560746e-02 6.80129556e-03]
  ...
  [1.26975874e-05 1.10934852e-05]
  [1.13728347e-05 1.07538253e-05]
  [1.12746438e-05 1.15659204e-05]]

 ...

 [[7.09619871e-06 7.65731238e-06]
  [2.39642886e-05 4.87407204e-04]
  [6.62838138e-05 7.19103822e-03]
  ...
  [8.84742894e-06 7.41559552e-06]
  [7.16832164e-06 7.06460924e-06]
  [7.44956469e-06 7.48281764e-06]]

 [[4.92710169e-05 5.37333108e-05]
  [1.02805825e-04 7.45833036e-04]
  [2.17940760e-04 6.67750835e-03]
  ...
  [1.65352207e-02 6.79496257e-03]
  [5.12321967e-05 4.92122381e-05]
  [5.09001511e-05 5.17323351e-05]]

 [[8.44145870e-06 9.17937086e-06]
  [2.61925197e-05 4.79288195e-04]
  [8.21833964e-05 6.76082075e-03]
  ...
  [1.02253653e-05 8.77571256e-06]
  [8.63762762e-06 8.44422448e-06]
  [8.93406650e-06 9.05547586e-06]]]
self._result: <april.anomalydetection.utils.result.AnomalyDetectionResult object at 0x00000287E5009B20>
self._result: <april.anomalydetection.utils.result.AnomalyDetectionResult object at 0x00000287E5009B20>
Eventlog id for wide-0.3-1 is 51
Length of LTN rows which will be excluded: 600
Epoch 1/6
40/40 [==============================] - 1s 9ms/step - loss: 0.2233 - accuracy: 0.2765 - val_loss: 0.1563 - val_accuracy: 1.0000
Epoch 2/6
40/40 [==============================] - 0s 7ms/step - loss: 0.0444 - accuracy: 0.8071 - val_loss: 0.0048 - val_accuracy: 1.0000
Epoch 3/6
40/40 [==============================] - 0s 6ms/step - loss: 0.0047 - accuracy: 0.8285 - val_loss: 0.0044 - val_accuracy: 1.0000
Epoch 4/6
40/40 [==============================] - 0s 7ms/step - loss: 0.0045 - accuracy: 0.8674 - val_loss: 0.0044 - val_accuracy: 1.0000
Epoch 5/6
40/40 [==============================] - 0s 6ms/step - loss: 0.0044 - accuracy: 0.8783 - val_loss: 0.0043 - val_accuracy: 1.0000
Epoch 6/6
40/40 [==============================] - 0s 6ms/step - loss: 0.0044 - accuracy: 0.8667 - val_loss: 0.0043 - val_accuracy: 1.0000
d:\LTNcoder\.out\models\wide-0.3-1_widedae-leaky-10_20250817-183813.302734.keras
Loading model wide-0.3-1_widedae-leaky-10_20250817-183813.302734 / <april.fs.ModelFile object at 0x000002877299B3A0> for event log wide-0.3-1 at path d:\LTNcoder\.out\models\wide-0.3-1_widedae-leaky-10_20250817-183813.302734.keras
Self.ad_: <april.anomalydetection.wideencoder.WideDAE-Leaky-10 object at 0x0000028772BD6F70>
Filtering dataset to 610 LTN rows.
Indices: [21, 38, 39, 60, 64, 95, 108, 117, 119, 134, 141, 142, 143, 149, 155, 156, 174, 185, 215, 237, 244, 255, 257, 262, 267, 268, 277, 295, 299, 307, 323, 324, 336, 359, 361, 364, 370, 377, 380, 389, 390, 393, 404, 417, 421, 425, 434, 445, 451, 460, 469, 475, 477, 480, 488, 492, 498, 499, 502, 510, 526, 545, 546, 549, 573, 575, 584, 587, 595, 608, 612, 616, 628, 630, 632, 640, 643, 652, 653, 656, 672, 673, 682, 694, 705, 712, 715, 733, 742, 744, 764, 766, 768, 772, 773, 776, 777, 784, 800, 807, 808, 820, 826, 829, 830, 851, 865, 866, 887, 891, 899, 900, 905, 906, 928, 931, 953, 962, 965, 967, 970, 979, 980, 990, 993, 1027, 1034, 1044, 1045, 1047, 1055, 1058, 1068, 1072, 1081, 1098, 1121, 1123, 1144, 1151, 1170, 1174, 1181, 1182, 1188, 1209, 1216, 1222, 1226, 1227, 1238, 1244, 1249, 1250, 1253, 1254, 1265, 1270, 1278, 1282, 1326, 1328, 1335, 1340, 1347, 1355, 1381, 1395, 1416, 1418, 1437, 1438, 1440, 1446, 1448, 1458, 1463, 1469, 1492, 1493, 1496, 1518, 1529, 1536, 1544, 1556, 1561, 1563, 1564, 1571, 1578, 1588, 1594, 1598, 1602, 1603, 1631, 1640, 1653, 1654, 1655, 1674, 1675, 1676, 1684, 1691, 1698, 1699, 1701, 1714, 1715, 1717, 1723, 1729, 1739, 1742, 1744, 1749, 1753, 1758, 1765, 1768, 1773, 1779, 1781, 1782, 1784, 1790, 1796, 1814, 1817, 1848, 1858, 1859, 1876, 1902, 1905, 1906, 1907, 1933, 1973, 1976, 1993, 1996, 2003, 2005, 2008, 2011, 2021, 2022, 2053, 2054, 2057, 2071, 2077, 2083, 2084, 2095, 2100, 2113, 2114, 2118, 2130, 2131, 2133, 2135, 2148, 2152, 2167, 2170, 2178, 2179, 2187, 2188, 2192, 2201, 2205, 2206, 2213, 2214, 2217, 2222, 2238, 2243, 2244, 2252, 2253, 2281, 2291, 2295, 2302, 2303, 2310, 2321, 2322, 2323, 2343, 2348, 2349, 2351, 2356, 2370, 2393, 2402, 2409, 2410, 2412, 2416, 2420, 2449, 2461, 2468, 2491, 2502, 2506, 2519, 2520, 2521, 2526, 2536, 2539, 2541, 2545, 2548, 2552, 2558, 2571, 2574, 2575, 2576, 2582, 2586, 2587, 2592, 2606, 2609, 2615, 2638, 2650, 2654, 2658, 2661, 2666, 2667, 2677, 2679, 2682, 2686, 2708, 2711, 2719, 2723, 2735, 2742, 2746, 2752, 2763, 2781, 2788, 2792, 2797, 2798, 2800, 2823, 2825, 2826, 2836, 2844, 2846, 2852, 2859, 2864, 2879, 2882, 2891, 2899, 2905, 2908, 2912, 2922, 2925, 2928, 2930, 2933, 2934, 2944, 2975, 2976, 2982, 2987, 2995, 2996, 2998, 3004, 3012, 3070, 3071, 3079, 3085, 3088, 3100, 3109, 3120, 3124, 3126, 3147, 3150, 3164, 3173, 3174, 3181, 3188, 3198, 3210, 3218, 3221, 3231, 3233, 3237, 3251, 3280, 3293, 3302, 3304, 3308, 3316, 3323, 3325, 3341, 3346, 3348, 3357, 3358, 3372, 3377, 3378, 3381, 3384, 3385, 3391, 3396, 3402, 3404, 3477, 3485, 3486, 3492, 3494, 3511, 3519, 3526, 3538, 3554, 3555, 3568, 3579, 3588, 3595, 3598, 3612, 3622, 3623, 3625, 3632, 3680, 3683, 3688, 3694, 3701, 3713, 3715, 3722, 3726, 3763, 3799, 3800, 3805, 3810, 3827, 3837, 3841, 3848, 3853, 3875, 3891, 3914, 3924, 3928, 3941, 3944, 3950, 3976, 3979, 3989, 3995, 4002, 4008, 4033, 4063, 4085, 4090, 4092, 4106, 4114, 4116, 4120, 4131, 4132, 4142, 4148, 4175, 4179, 4181, 4184, 4188, 4192, 4223, 4237, 4251, 4254, 4260, 4262, 4276, 4291, 4303, 4328, 4339, 4342, 4351, 4382, 4390, 4399, 4409, 4418, 4424, 4428, 4433, 4441, 4443, 4454, 4479, 4488, 4495, 4502, 4505, 4508, 4526, 4532, 4540, 4541, 4562, 4565, 4566, 4583, 4587, 4594, 4603, 4609, 4615, 4618, 4623, 4627, 4637, 4645, 4647, 4659, 4668, 4671, 4674, 4689, 4711, 4725, 4726, 4729, 4735, 4743, 4752, 4755, 4757, 4765, 4776, 4790, 4792, 4795, 4800, 4808, 4810, 4811, 4812, 4813, 4822, 4828, 4833, 4837, 4864, 4885, 4892, 4893, 4894, 4903, 4913, 4932, 4936, 4948, 4956, 4963, 4983, 4991, 4996, 4998]
Evaluation dataset shape: (610, 12, 2)
20/20 [==============================] - 0s 2ms/step
wide-0.3-1 [ 58. 141.]
wide-0.3-1 [ 58. 141.]
wide-0.3-1 [ 58. 141.]
wide-0.3-1 [ 58. 141.]
Anomaly detection result for wide-0.3-1_widedae-leaky-10_20250817-183813.302734 on wide-0.3-1 with widedae-leaky-10 saved to d:\LTNcoder\.out\.cache\results\wide-0.3-1_widedae-leaky-10_20250817-183813.302734.result
self._result: <april.anomalydetection.utils.result.AnomalyDetectionResult object at 0x000002877119E460>
self.result.scores: [[[5.69751819e-06 5.97553390e-06]
  [1.63690020e-05 3.34027980e-04]
  [5.32140402e-05 5.84412226e-03]
  ...
  [6.37982339e-06 7.70467159e-06]
  [6.53886264e-06 6.13736120e-06]
  [5.98776569e-06 6.75911633e-06]]

 [[3.91284584e-06 4.09924996e-06]
  [1.29612472e-05 2.94917903e-04]
  [4.15341310e-05 5.87215601e-03]
  ...
  [4.39652968e-06 5.35412983e-06]
  [4.49686650e-06 4.24650943e-06]
  [4.07278003e-06 4.71270278e-06]]

 [[8.12153849e-06 8.41796736e-06]
  [3.33790034e-02 1.17270760e-02]
  [3.26700993e-02 6.94101583e-03]
  ...
  [9.16627050e-06 1.08341792e-05]
  [9.51683614e-06 8.73592944e-06]
  [8.59453849e-06 9.83571590e-06]]

 ...

 [[6.57696592e-06 6.68961638e-06]
  [2.01638322e-05 3.97022814e-04]
  [5.47686286e-05 7.17949681e-03]
  ...
  [7.27249926e-06 8.58849307e-06]
  [7.29976955e-06 6.99431030e-06]
  [6.97189171e-06 7.78681715e-06]]

 [[3.55814373e-05 3.69460868e-05]
  [7.07386207e-05 5.63878042e-04]
  [1.66323560e-04 6.82699494e-03]
  ...
  [1.69709250e-02 6.83253445e-03]
  [4.13187045e-05 3.88628214e-05]
  [3.90865462e-05 4.29077736e-05]]

 [[6.47948718e-06 6.64658410e-06]
  [1.75533369e-05 3.82906728e-04]
  [5.68480791e-05 6.89044828e-03]
  ...
  [7.10102950e-06 8.44215356e-06]
  [7.36098127e-06 6.88860700e-06]
  [6.76954687e-06 7.65413279e-06]]]
self._result: <april.anomalydetection.utils.result.AnomalyDetectionResult object at 0x000002877119E460>
self._result: <april.anomalydetection.utils.result.AnomalyDetectionResult object at 0x000002877119E460>
Eventlog id for wide-0.3-1 is 51
Length of LTN rows which will be excluded: 585
Epoch 1/6
40/40 [==============================] - 1s 10ms/step - loss: 0.2197 - accuracy: 0.0086 - val_loss: 0.1459 - val_accuracy: 0.0000e+00
Epoch 2/6
40/40 [==============================] - 0s 7ms/step - loss: 0.0391 - accuracy: 0.0730 - val_loss: 0.0048 - val_accuracy: 0.0000e+00
Epoch 3/6
40/40 [==============================] - 0s 7ms/step - loss: 0.0047 - accuracy: 0.2630 - val_loss: 0.0044 - val_accuracy: 0.0000e+00
Epoch 4/6
40/40 [==============================] - 0s 7ms/step - loss: 0.0045 - accuracy: 0.3836 - val_loss: 0.0044 - val_accuracy: 0.0023
Epoch 5/6
40/40 [==============================] - 0s 7ms/step - loss: 0.0044 - accuracy: 0.4176 - val_loss: 0.0044 - val_accuracy: 0.0023
Epoch 6/6
40/40 [==============================] - 0s 6ms/step - loss: 0.0044 - accuracy: 0.4425 - val_loss: 0.0043 - val_accuracy: 0.0068
d:\LTNcoder\.out\models\wide-0.3-1_widedae-leaky-25_20250817-183815.986790.keras
Loading model wide-0.3-1_widedae-leaky-25_20250817-183815.986790 / <april.fs.ModelFile object at 0x00000287E4EC81C0> for event log wide-0.3-1 at path d:\LTNcoder\.out\models\wide-0.3-1_widedae-leaky-25_20250817-183815.986790.keras
Self.ad_: <april.anomalydetection.wideencoder.WideDAE-Leaky-25 object at 0x0000028770664850>
Filtering dataset to 610 LTN rows.
Indices: [21, 38, 39, 60, 64, 95, 108, 117, 119, 134, 141, 142, 143, 149, 155, 156, 174, 185, 215, 237, 244, 255, 257, 262, 267, 268, 277, 295, 299, 307, 323, 324, 336, 359, 361, 364, 370, 377, 380, 389, 390, 393, 404, 417, 421, 425, 434, 445, 451, 460, 469, 475, 477, 480, 488, 492, 498, 499, 502, 510, 526, 545, 546, 549, 573, 575, 584, 587, 595, 608, 612, 616, 628, 630, 632, 640, 643, 652, 653, 656, 672, 673, 682, 694, 705, 712, 715, 733, 742, 744, 764, 766, 768, 772, 773, 776, 777, 784, 800, 807, 808, 820, 826, 829, 830, 851, 865, 866, 887, 891, 899, 900, 905, 906, 928, 931, 953, 962, 965, 967, 970, 979, 980, 990, 993, 1027, 1034, 1044, 1045, 1047, 1055, 1058, 1068, 1072, 1081, 1098, 1121, 1123, 1144, 1151, 1170, 1174, 1181, 1182, 1188, 1209, 1216, 1222, 1226, 1227, 1238, 1244, 1249, 1250, 1253, 1254, 1265, 1270, 1278, 1282, 1326, 1328, 1335, 1340, 1347, 1355, 1381, 1395, 1416, 1418, 1437, 1438, 1440, 1446, 1448, 1458, 1463, 1469, 1492, 1493, 1496, 1518, 1529, 1536, 1544, 1556, 1561, 1563, 1564, 1571, 1578, 1588, 1594, 1598, 1602, 1603, 1631, 1640, 1653, 1654, 1655, 1674, 1675, 1676, 1684, 1691, 1698, 1699, 1701, 1714, 1715, 1717, 1723, 1729, 1739, 1742, 1744, 1749, 1753, 1758, 1765, 1768, 1773, 1779, 1781, 1782, 1784, 1790, 1796, 1814, 1817, 1848, 1858, 1859, 1876, 1902, 1905, 1906, 1907, 1933, 1973, 1976, 1993, 1996, 2003, 2005, 2008, 2011, 2021, 2022, 2053, 2054, 2057, 2071, 2077, 2083, 2084, 2095, 2100, 2113, 2114, 2118, 2130, 2131, 2133, 2135, 2148, 2152, 2167, 2170, 2178, 2179, 2187, 2188, 2192, 2201, 2205, 2206, 2213, 2214, 2217, 2222, 2238, 2243, 2244, 2252, 2253, 2281, 2291, 2295, 2302, 2303, 2310, 2321, 2322, 2323, 2343, 2348, 2349, 2351, 2356, 2370, 2393, 2402, 2409, 2410, 2412, 2416, 2420, 2449, 2461, 2468, 2491, 2502, 2506, 2519, 2520, 2521, 2526, 2536, 2539, 2541, 2545, 2548, 2552, 2558, 2571, 2574, 2575, 2576, 2582, 2586, 2587, 2592, 2606, 2609, 2615, 2638, 2650, 2654, 2658, 2661, 2666, 2667, 2677, 2679, 2682, 2686, 2708, 2711, 2719, 2723, 2735, 2742, 2746, 2752, 2763, 2781, 2788, 2792, 2797, 2798, 2800, 2823, 2825, 2826, 2836, 2844, 2846, 2852, 2859, 2864, 2879, 2882, 2891, 2899, 2905, 2908, 2912, 2922, 2925, 2928, 2930, 2933, 2934, 2944, 2975, 2976, 2982, 2987, 2995, 2996, 2998, 3004, 3012, 3070, 3071, 3079, 3085, 3088, 3100, 3109, 3120, 3124, 3126, 3147, 3150, 3164, 3173, 3174, 3181, 3188, 3198, 3210, 3218, 3221, 3231, 3233, 3237, 3251, 3280, 3293, 3302, 3304, 3308, 3316, 3323, 3325, 3341, 3346, 3348, 3357, 3358, 3372, 3377, 3378, 3381, 3384, 3385, 3391, 3396, 3402, 3404, 3477, 3485, 3486, 3492, 3494, 3511, 3519, 3526, 3538, 3554, 3555, 3568, 3579, 3588, 3595, 3598, 3612, 3622, 3623, 3625, 3632, 3680, 3683, 3688, 3694, 3701, 3713, 3715, 3722, 3726, 3763, 3799, 3800, 3805, 3810, 3827, 3837, 3841, 3848, 3853, 3875, 3891, 3914, 3924, 3928, 3941, 3944, 3950, 3976, 3979, 3989, 3995, 4002, 4008, 4033, 4063, 4085, 4090, 4092, 4106, 4114, 4116, 4120, 4131, 4132, 4142, 4148, 4175, 4179, 4181, 4184, 4188, 4192, 4223, 4237, 4251, 4254, 4260, 4262, 4276, 4291, 4303, 4328, 4339, 4342, 4351, 4382, 4390, 4399, 4409, 4418, 4424, 4428, 4433, 4441, 4443, 4454, 4479, 4488, 4495, 4502, 4505, 4508, 4526, 4532, 4540, 4541, 4562, 4565, 4566, 4583, 4587, 4594, 4603, 4609, 4615, 4618, 4623, 4627, 4637, 4645, 4647, 4659, 4668, 4671, 4674, 4689, 4711, 4725, 4726, 4729, 4735, 4743, 4752, 4755, 4757, 4765, 4776, 4790, 4792, 4795, 4800, 4808, 4810, 4811, 4812, 4813, 4822, 4828, 4833, 4837, 4864, 4885, 4892, 4893, 4894, 4903, 4913, 4932, 4936, 4948, 4956, 4963, 4983, 4991, 4996, 4998]
Evaluation dataset shape: (610, 12, 2)
20/20 [==============================] - 0s 1ms/step
wide-0.3-1 [ 58. 141.]
wide-0.3-1 [ 58. 141.]
wide-0.3-1 [ 58. 141.]
wide-0.3-1 [ 58. 141.]
Anomaly detection result for wide-0.3-1_widedae-leaky-25_20250817-183815.986790 on wide-0.3-1 with widedae-leaky-25 saved to d:\LTNcoder\.out\.cache\results\wide-0.3-1_widedae-leaky-25_20250817-183815.986790.result
self._result: <april.anomalydetection.utils.result.AnomalyDetectionResult object at 0x0000028772B2F310>
self.result.scores: [[[3.29152931e-06 3.56197165e-06]
  [1.77304373e-05 2.51113233e-04]
  [4.13047164e-05 5.89423534e-03]
  ...
  [5.11719645e-06 3.72799923e-06]
  [3.62702690e-06 3.82466396e-06]
  [3.71825968e-06 3.08234644e-06]]

 [[3.50396726e-06 3.79573476e-06]
  [1.77761140e-05 2.63204711e-04]
  [3.95748757e-05 5.85094141e-03]
  ...
  [5.49197694e-06 3.93263053e-06]
  [3.83453744e-06 4.03070635e-06]
  [3.89931211e-06 3.25253018e-06]]

 [[1.11228655e-05 1.21293078e-05]
  [3.28859985e-02 1.16878757e-02]
  [3.21306475e-02 6.79818820e-03]
  ...
  [1.63106761e-05 1.23852424e-05]
  [1.23735254e-05 1.29696373e-05]
  [1.23823875e-05 1.06284033e-05]]

 ...

 [[5.08490393e-06 5.39914163e-06]
  [1.90535775e-05 3.07951268e-04]
  [4.77790127e-05 7.24624842e-03]
  ...
  [8.11968039e-06 5.47459058e-06]
  [5.45320609e-06 5.73654097e-06]
  [5.65522942e-06 4.67115797e-06]]


In [47]:
print(AD) #Evaluator dependso on AD

{'binetv0': <class 'april.anomalydetection.binet.binet.BINetv0'>, 'binetv1': <class 'april.anomalydetection.binet.binet.BINetv1'>, 'binetv2': <class 'april.anomalydetection.binet.binet.BINetv2'>, 'binetv3': <class 'april.anomalydetection.binet.binet.BINetv3'>, 'likelihood': <class 'april.anomalydetection.boehmer.BoehmerLikelihoodAnomalyDetector'>, 'dae': <class 'april.anomalydetection.autoencoder.DAE'>, 'daeltn': <class 'april.anomalydetection.autoencoder.DAELTN'>, 'daeltnfrozen': <class 'april.anomalydetection.autoencoder.DAELTNFROZEN'>, 'likelihood+': <class 'april.anomalydetection.boehmer.LikelihoodPlusAnomalyDetector'>, 'naive': <class 'april.anomalydetection.bezerra.NaiveAnomalyDetector'>, 'naive+': <class 'april.anomalydetection.bezerra.NaivePlusAnomalyDetector'>, 'one-class-svm': <class 'april.anomalydetection.basic.OneClassSVM'>, 'perfect': <class 'april.anomalydetection.basic.PerfectAnomalyDetector'>, 'random': <class 'april.anomalydetection.basic.RandomAnomalyDetector'>, 'sampling': <class 'april.anomalydetection.bezerra.SamplingAnomalyDetector'>, 't-stide': <class 'april.anomalydetection.warrender.TStide'>, 't-stide+': <class 'april.anomalydetection.warrender.TStidePlus'>, 'widedae': <class 'april.anomalydetection.wideencoder.WideDAE'>, 'widedae-leaky-10': <class 'april.anomalydetection.wideencoder.WideDAE-Leaky-10'>, 'widedae-leaky-100': <class 'april.anomalydetection.wideencoder.WideDAE-Leaky-100'>, 'widedae-leaky-150': <class 'april.anomalydetection.wideencoder.WideDAE-Leaky-150'>, 'widedae-leaky-200': <class 'april.anomalydetection.wideencoder.WideDAE-Leaky-200'>, 'widedae-leaky-25': <class 'april.anomalydetection.wideencoder.WideDAE-Leaky-25'>, 'widedae-leaky-250': <class 'april.anomalydetection.wideencoder.WideDAE-Leaky-250'>, 'widedae-leaky-300': <class 'april.anomalydetection.wideencoder.WideDAE-Leaky-300'>, 'widedae-leaky-50': <class 'april.anomalydetection.wideencoder.WideDAE-Leaky-50'>, 'Wideltn': <class 'april.anomalydetection.wideencoder.WideLTN'>, 'wideltnfrozen': <class 'april.anomalydetection.wideencoder.WideLTNFROZEN'>, 'wideltnfrozen-10': <class 'april.anomalydetection.wideencoder.WideLTNFROZEN-10'>, 'wideltnfrozen-100': <class 'april.anomalydetection.wideencoder.WideLTNFROZEN-100'>, 'wideltnfrozen-150': <class 'april.anomalydetection.wideencoder.WideLTNFROZEN-150'>, 'wideltnfrozen-200': <class 'april.anomalydetection.wideencoder.WideLTNFROZEN-200'>, 'wideltnfrozen-25': <class 'april.anomalydetection.wideencoder.WideLTNFROZEN-25'>, 'wideltnfrozen-250': <class 'april.anomalydetection.wideencoder.WideLTNFROZEN-250'>, 'wideltnfrozen-300': <class 'april.anomalydetection.wideencoder.WideLTNFROZEN-300'>, 'wideltnfrozen-50': <class 'april.anomalydetection.wideencoder.WideLTNFROZEN-50'>}

# Evaluation

In [48]:
heuristics = [h for h in Heuristic.keys() if h not in [Heuristic.DEFAULT, Heuristic.MANUAL, Heuristic.RATIO,
                                                       Heuristic.MEDIAN, Heuristic.MEAN]]
params = [(Base.SCORES, Heuristic.DEFAULT, Strategy.SINGLE), *itertools.product([Base.SCORES], heuristics, Strategy.keys())]

In [49]:
def _evaluate(params):
    # print(f"Evaluating {params}...")
    e, base, heuristic, strategy = params

    session = Session(get_engine())
    model = session.query(Model).filter_by(file_name=e.model_file.name).first()
    session.close()
    # print(f"Model {model} loaded from Session.")

    if Model is None:
        print(f"Models from session: {model}")
    # Generate evaluation frames
    y_pred = e.binarizer.binarize(base=base, heuristic=heuristic, strategy=strategy, go_backwards=False)
    y_true = e.binarizer.get_targets()

    evaluations = []
    for axis in [0, 1, 2]:
        # print(f"Evaluating axis {axis}...")
        for i, attribute_name in enumerate(e.dataset.attribute_keys):
            # print(f"Evaluating attribute {attribute_name}...")
            def get_evaluation(label, precision, recall, f1):
                return Evaluation(model_id=model.id, file_name=model.file_name,
                                  label=label, perspective=perspective, attribute_name=attribute_name,
                                  axis=axis, base=base, heuristic=heuristic, strategy=strategy,
                                  precision=precision, recall=recall, f1=f1)

            perspective = 'Control Flow' if i == 0 else 'Data'
            if i > 0 and not e.ad_.supports_attributes:
                # print(f"Skipping attribute {attribute_name} for model {model} as it does not support attributes.")
                evaluations.append(get_evaluation('Normal', 0.0, 0.0, 0.0))
                evaluations.append(get_evaluation('Anomaly', 0.0, 0.0, 0.0))
            else:
                # print(f"Evaluating attribute {attribute_name} for model {model}...")
                yp = label_collapse(y_pred[:, :, i:i + 1], axis=axis).compressed()
                yt = label_collapse(y_true[:, :, i:i + 1], axis=axis).compressed()
                p, r, f, _ = metrics.precision_recall_fscore_support(yt, yp, labels=[0, 1])
                evaluations.append(get_evaluation('Normal', p[0], r[0], f[0]))
                evaluations.append(get_evaluation('Anomaly', p[1], r[1], f[1]))

    return evaluations

def evaluate(model_name):
    print(f"Evaluating {model_name}...")
    e = Evaluator(model_name)
    print(f"{e} loaded.")
    # print attributes of e
    print(f"e.model_file: {e.model_file}")
    print(f"e.model_name: {e.model_name}")
    print(f"e.eventlog_name: {e.eventlog_name}")
    print(f"e.dataset: {e.dataset}")
    print(f"e.result: {e.result}")
    
    
    _params = []
    for base, heuristic, strategy in params:
        if e.dataset.num_attributes == 1 and strategy in [Strategy.ATTRIBUTE, Strategy.POSITION_ATTRIBUTE]:
            continue
        if isinstance(e.ad_, BINet) and e.ad_.version == 0:
            continue
        if heuristic is not None and heuristic not in e.ad_.supported_heuristics:
            continue
        if strategy is not None and strategy not in e.ad_.supported_strategies:
            continue
        if base is not None and base not in e.ad_.supported_bases:
            continue
        # print(f"Adding parameters: {e}, {base}, {heuristic}, {strategy}")
        _params.append([e, base, heuristic, strategy])
    
    print(f"{_params} parameters to evaluate.")

    return [_e for p in _params for _e in _evaluate(p)]

In [50]:
models = sorted([m.name for m in get_model_files() if m.p == 0.3])# and 'real' in m.name])
print(f"Available Models: {models}")
evaluations = []
for model in tqdm(models, desc='Evaluate'):
    e = evaluate(model)
    evaluations.append(e)
# Write to database
session = Session(get_engine())
for e in evaluations:
    session.bulk_save_objects(e)
    session.commit()
session.close()

Available Models: ['wide-0.3-1_widedae-leaky-100_20250817-183821.443245', 'wide-0.3-1_widedae-leaky-10_20250817-183813.302734', 'wide-0.3-1_widedae-leaky-150_20250817-183825.117052', 'wide-0.3-1_widedae-leaky-200_20250817-183828.107237', 'wide-0.3-1_widedae-leaky-250_20250817-183831.013457', 'wide-0.3-1_widedae-leaky-25_20250817-183815.986790', 'wide-0.3-1_widedae-leaky-300_20250817-183833.923650', 'wide-0.3-1_widedae-leaky-50_20250817-183818.730522', 'wide-0.3-1_widedae_20250817-183810.336025', 'wide-0.3-1_wideltnfrozen-100_20250817-183923.660710', 'wide-0.3-1_wideltnfrozen-10_20250817-183836.932309', 'wide-0.3-1_wideltnfrozen-150_20250817-183939.091597', 'wide-0.3-1_wideltnfrozen-200_20250817-184003.839918', 'wide-0.3-1_wideltnfrozen-250_20250817-184029.383340', 'wide-0.3-1_wideltnfrozen-25_20250817-183852.210684', 'wide-0.3-1_wideltnfrozen-300_20250817-184050.250515', 'wide-0.3-1_wideltnfrozen-50_20250817-183907.950542']

Evaluate:   0%|          | 0/17 [00:00<?, ?it/s]

Evaluating wide-0.3-1_widedae-leaky-100_20250817-183821.443245...
Loading model wide-0.3-1_widedae-leaky-100_20250817-183821.443245 / <april.fs.ModelFile object at 0x0000028772D3D520> for event log wide-0.3-1 at path d:\LTNcoder\.out\models\wide-0.3-1_widedae-leaky-100_20250817-183821.443245.keras
Self.ad_: <april.anomalydetection.wideencoder.WideDAE-Leaky-100 object at 0x0000028772D3D8B0>
<april.wideevaluator.Evaluator object at 0x0000028772D3D850> loaded.
e.model_file: d:\LTNcoder\.out\models\wide-0.3-1_widedae-leaky-100_20250817-183821.443245.keras
e.model_name: wide-0.3-1_widedae-leaky-100_20250817-183821.443245
e.eventlog_name: wide-0.3-1
Filtering dataset to 610 LTN rows.
Indices: [21, 38, 39, 60, 64, 95, 108, 117, 119, 134, 141, 142, 143, 149, 155, 156, 174, 185, 215, 237, 244, 255, 257, 262, 267, 268, 277, 295, 299, 307, 323, 324, 336, 359, 361, 364, 370, 377, 380, 389, 390, 393, 404, 417, 421, 425, 434, 445, 451, 460, 469, 475, 477, 480, 488, 492, 498, 499, 502, 510, 526, 545, 546, 549, 573, 575, 584, 587, 595, 608, 612, 616, 628, 630, 632, 640, 643, 652, 653, 656, 672, 673, 682, 694, 705, 712, 715, 733, 742, 744, 764, 766, 768, 772, 773, 776, 777, 784, 800, 807, 808, 820, 826, 829, 830, 851, 865, 866, 887, 891, 899, 900, 905, 906, 928, 931, 953, 962, 965, 967, 970, 979, 980, 990, 993, 1027, 1034, 1044, 1045, 1047, 1055, 1058, 1068, 1072, 1081, 1098, 1121, 1123, 1144, 1151, 1170, 1174, 1181, 1182, 1188, 1209, 1216, 1222, 1226, 1227, 1238, 1244, 1249, 1250, 1253, 1254, 1265, 1270, 1278, 1282, 1326, 1328, 1335, 1340, 1347, 1355, 1381, 1395, 1416, 1418, 1437, 1438, 1440, 1446, 1448, 1458, 1463, 1469, 1492, 1493, 1496, 1518, 1529, 1536, 1544, 1556, 1561, 1563, 1564, 1571, 1578, 1588, 1594, 1598, 1602, 1603, 1631, 1640, 1653, 1654, 1655, 1674, 1675, 1676, 1684, 1691, 1698, 1699, 1701, 1714, 1715, 1717, 1723, 1729, 1739, 1742, 1744, 1749, 1753, 1758, 1765, 1768, 1773, 1779, 1781, 1782, 1784, 1790, 1796, 1814, 1817, 1848, 1858, 1859, 1876, 1902, 1905, 1906, 1907, 1933, 1973, 1976, 1993, 1996, 2003, 2005, 2008, 2011, 2021, 2022, 2053, 2054, 2057, 2071, 2077, 2083, 2084, 2095, 2100, 2113, 2114, 2118, 2130, 2131, 2133, 2135, 2148, 2152, 2167, 2170, 2178, 2179, 2187, 2188, 2192, 2201, 2205, 2206, 2213, 2214, 2217, 2222, 2238, 2243, 2244, 2252, 2253, 2281, 2291, 2295, 2302, 2303, 2310, 2321, 2322, 2323, 2343, 2348, 2349, 2351, 2356, 2370, 2393, 2402, 2409, 2410, 2412, 2416, 2420, 2449, 2461, 2468, 2491, 2502, 2506, 2519, 2520, 2521, 2526, 2536, 2539, 2541, 2545, 2548, 2552, 2558, 2571, 2574, 2575, 2576, 2582, 2586, 2587, 2592, 2606, 2609, 2615, 2638, 2650, 2654, 2658, 2661, 2666, 2667, 2677, 2679, 2682, 2686, 2708, 2711, 2719, 2723, 2735, 2742, 2746, 2752, 2763, 2781, 2788, 2792, 2797, 2798, 2800, 2823, 2825, 2826, 2836, 2844, 2846, 2852, 2859, 2864, 2879, 2882, 2891, 2899, 2905, 2908, 2912, 2922, 2925, 2928, 2930, 2933, 2934, 2944, 2975, 2976, 2982, 2987, 2995, 2996, 2998, 3004, 3012, 3070, 3071, 3079, 3085, 3088, 3100, 3109, 3120, 3124, 3126, 3147, 3150, 3164, 3173, 3174, 3181, 3188, 3198, 3210, 3218, 3221, 3231, 3233, 3237, 3251, 3280, 3293, 3302, 3304, 3308, 3316, 3323, 3325, 3341, 3346, 3348, 3357, 3358, 3372, 3377, 3378, 3381, 3384, 3385, 3391, 3396, 3402, 3404, 3477, 3485, 3486, 3492, 3494, 3511, 3519, 3526, 3538, 3554, 3555, 3568, 3579, 3588, 3595, 3598, 3612, 3622, 3623, 3625, 3632, 3680, 3683, 3688, 3694, 3701, 3713, 3715, 3722, 3726, 3763, 3799, 3800, 3805, 3810, 3827, 3837, 3841, 3848, 3853, 3875, 3891, 3914, 3924, 3928, 3941, 3944, 3950, 3976, 3979, 3989, 3995, 4002, 4008, 4033, 4063, 4085, 4090, 4092, 4106, 4114, 4116, 4120, 4131, 4132, 4142, 4148, 4175, 4179, 4181, 4184, 4188, 4192, 4223, 4237, 4251, 4254, 4260, 4262, 4276, 4291, 4303, 4328, 4339, 4342, 4351, 4382, 4390, 4399, 4409, 4418, 4424, 4428, 4433, 4441, 4443, 4454, 4479, 4488, 4495, 4502, 4505, 4508, 4526, 4532, 4540, 4541, 4562, 4565, 4566, 4583, 4587, 4594, 4603, 4609, 4615, 4618, 4623, 4627, 4637, 4645, 4647, 4659, 4668, 4671, 4674, 4689, 4711, 4725, 4726, 4729, 4735, 4743, 4752, 4755, 4757, 4765, 4776, 4790, 4792, 4795, 4800, 4808, 4810, 4811, 4812, 4813, 4822, 4828, 4833, 4837, 4864, 4885, 4892, 4893, 4894, 4903, 4913, 4932, 4936, 4948, 4956, 4963, 4983, 4991, 4996, 4998]
e.dataset: <april.dataset.Dataset object at 0x0000028772D3D910>
Loading anomaly detection result
self._result: <april.anomalydetection.utils.result.AnomalyDetectionResult object at 0x0000028772D3DEB0>
e.result: <april.anomalydetection.utils.result.AnomalyDetectionResult object at 0x0000028772D3DEB0>
[[<april.wideevaluator.Evaluator object at 0x0000028772D3D850>, 'scores', 'best', 'single'], [<april.wideevaluator.Evaluator object at 0x0000028772D3D850>, 'scores', 'best', 'attribute'], [<april.wideevaluator.Evaluator object at 0x0000028772D3D850>, 'scores', 'best', 'position'], [<april.wideevaluator.Evaluator object at 0x0000028772D3D850>, 'scores', 'best', 'position_attribute'], [<april.wideevaluator.Evaluator object at 0x0000028772D3D850>, 'scores', 'elbow', 'single'], [<april.wideevaluator.Evaluator object at 0x0000028772D3D850>, 'scores', 'elbow', 'attribute'], [<april.wideevaluator.Evaluator object at 0x0000028772D3D850>, 'scores', 'elbow', 'position'], [<april.wideevaluator.Evaluator object at 0x0000028772D3D850>, 'scores', 'elbow', 'position_attribute'], [<april.wideevaluator.Evaluator object at 0x0000028772D3D850>, 'scores', 'broken_elbow', 'single'], [<april.wideevaluator.Evaluator object at 0x0000028772D3D850>, 'scores', 'broken_elbow', 'attribute'], [<april.wideevaluator.Evaluator object at 0x0000028772D3D850>, 'scores', 'broken_elbow', 'position'], [<april.wideevaluator.Evaluator object at 0x0000028772D3D850>, 'scores', 'broken_elbow', 'position_attribute'], [<april.wideevaluator.Evaluator object at 0x0000028772D3D850>, 'scores', 'stable_left', 'single'], [<april.wideevaluator.Evaluator object at 0x0000028772D3D850>, 'scores', 'stable_left', 'attribute'], [<april.wideevaluator.Evaluator object at 0x0000028772D3D850>, 'scores', 'stable_left', 'position'], [<april.wideevaluator.Evaluator object at 0x0000028772D3D850>, 'scores', 'stable_left', 'position_attribute'], [<april.wideevaluator.Evaluator object at 0x0000028772D3D850>, 'scores', 'stable_mean', 'single'], [<april.wideevaluator.Evaluator object at 0x0000028772D3D850>, 'scores', 'stable_mean', 'attribute'], [<april.wideevaluator.Evaluator object at 0x0000028772D3D850>, 'scores', 'stable_mean', 'position'], [<april.wideevaluator.Evaluator object at 0x0000028772D3D850>, 'scores', 'stable_mean', 'position_attribute'], [<april.wideevaluator.Evaluator object at 0x0000028772D3D850>, 'scores', 'stable_right', 'single'], [<april.wideevaluator.Evaluator object at 0x0000028772D3D850>, 'scores', 'stable_right', 'attribute'], [<april.wideevaluator.Evaluator object at 0x0000028772D3D850>, 'scores', 'stable_right', 'position'], [<april.wideevaluator.Evaluator object at 0x0000028772D3D850>, 'scores', 'stable_right', 'position_attribute']] parameters to evaluate.
self._result: <april.anomalydetection.utils.result.AnomalyDetectionResult object at 0x0000028772D3DEB0>
self._result: <april.anomalydetection.utils.result.AnomalyDetectionResult object at 0x0000028772D3DEB0>
Evaluation dataset shape: (610, 12, 2)
Result in Binarizer.__init__: None
Scores in Binarizer.binarize: None and shape: None
Using result.scores: [[[2.75007119e-06 2.47149615e-06]
  [1.49225061e-05 3.56343429e-04]
  [3.74017109e-05 5.91769628e-03]
  ...
  [3.70947555e-06 2.71421300e-06]
  [2.68737699e-06 2.63530524e-06]
  [2.53050325e-06 2.47446019e-06]]

 [[2.72162038e-06 2.42528904e-06]
  [1.43681245e-05 3.51952680e-04]
  [3.68649635e-05 5.89000667e-03]
  ...
  [3.69087707e-06 2.67805694e-06]
  [2.63525089e-06 2.62548883e-06]
  [2.50425273e-06 2.44820399e-06]]

 [[9.02092052e-06 8.11666632e-06]
  [3.29293311e-02 1.15207545e-02]
  [3.22100706e-02 6.77211257e-03]
  ...
  [1.16274477e-05 8.80699099e-06]
  [8.77520415e-06 8.72896908e-06]
  [8.33869672e-06 8.09178528e-06]]

 ...

 [[8.36677100e-06 7.45488387e-06]
  [2.83537320e-05 4.86416073e-04]
  [7.00538003e-05 7.26263504e-03]
  ...
  [9.99885924e-06 8.13535189e-06]
  [8.30960289e-06 8.19517481e-06]
  [7.53429322e-06 7.87021600e-06]]

 [[3.84747909e-05 3.48140784e-05]
  [9.23409534e-05 6.71042129e-04]
  [1.36349321e-04 6.96689123e-03]
  ...
  [1.65899135e-02 6.97882380e-03]
  [3.70924754e-05 3.76778771e-05]
  [3.55551747e-05 3.52286661e-05]]

 [[5.64694164e-06 5.07179448e-06]
  [2.18026817e-05 4.11751564e-04]
  [4.75140514e-05 7.03595858e-03]
  ...
  [7.18936462e-06 5.57014300e-06]
  [5.54583812e-06 5.44419163e-06]
  [5.25270343e-06 5.13590203e-06]]] and shape: (610, 12, 2)
Masked scores in Binarizer.binarize: [[[2.7500711894390406e-06 2.471496145517449e-06]
  [1.4922506125003565e-05 0.0003563434293027967]
  [3.740171086974442e-05 0.0059176962822675705]
  ...
  [-- --]
  [-- --]
  [-- --]]

 [[2.72162037617818e-06 2.4252890398202e-06]
  [1.4368124539032578e-05 0.0003519526799209416]
  [3.686496347654611e-05 0.00589000666514039]
  ...
  [-- --]
  [-- --]
  [-- --]]

 [[9.020920515467878e-06 8.116666322166566e-06]
  [0.03292933106422424 0.011520754545927048]
  [0.03221007063984871 0.006772112566977739]
  ...
  [-- --]
  [-- --]
  [-- --]]

 ...

 [[8.366770998691209e-06 7.454883871105267e-06]
  [2.8353731977404095e-05 0.0004864160728175193]
  [7.005380030022934e-05 0.0072626350447535515]
  ...
  [-- --]
  [-- --]
  [-- --]]

 [[3.8474790926557034e-05 3.4814078389899805e-05]
  [9.234095341525972e-05 0.0006710421293973923]
  [0.00013634932111017406 0.00696689123287797]
  ...
  [0.01658991351723671 0.0069788238033652306]
  [-- --]
  [-- --]]

 [[5.646941644954495e-06 5.071794475952629e-06]
  [2.180268165830057e-05 0.00041175156366080046]
  [4.7514051402686164e-05 0.007035958580672741]
  ...
  [-- --]
  [-- --]
  [-- --]]] and shape: (610, 12, 2)
self._result: <april.anomalydetection.utils.result.AnomalyDetectionResult object at 0x0000028772D3DEB0>
self._result: <april.anomalydetection.utils.result.AnomalyDetectionResult object at 0x0000028772D3DEB0>
Scores in Binarizer.binarize: None and shape: None
Using result.scores: [[[2.75007119e-06 2.47149615e-06]
  [1.49225061e-05 3.56343429e-04]
  [3.74017109e-05 5.91769628e-03]
  ...
  [3.70947555e-06 2.71421300e-06]
  [2.68737699e-06 2.63530524e-06]
  [2.53050325e-06 2.47446019e-06]]

 [[2.72162038e-06 2.42528904e-06]
  [1.43681245e-05 3.51952680e-04]
  [3.68649635e-05 5.89000667e-03]
  ...
  [3.69087707e-06 2.67805694e-06]
  [2.63525089e-06 2.62548883e-06]
  [2.50425273e-06 2.44820399e-06]]

 [[9.02092052e-06 8.11666632e-06]
  [3.29293311e-02 1.15207545e-02]
  [3.22100706e-02 6.77211257e-03]
  ...
  [1.16274477e-05 8.80699099e-06]
  [8.77520415e-06 8.72896908e-06]
  [8.33869672e-06 8.09178528e-06]]

 ...

 [[8.36677100e-06 7.45488387e-06]
  [2.83537320e-05 4.86416073e-04]
  [7.00538003e-05 7.26263504e-03]
  ...
  [9.99885924e-06 8.13535189e-06]
  [8.30960289e-06 8.19517481e-06]
  [7.53429322e-06 7.87021600e-06]]

 [[3.84747909e-05 3.48140784e-05]
  [9.23409534e-05 6.71042129e-04]
  [1.36349321e-04 6.96689123e-03]
  ...
  [1.65899135e-02 6.97882380e-03]
  [3.70924754e-05 3.76778771e-05]
  [3.55551747e-05 3.52286661e-05]]

 [[5.64694164e-06 5.07179448e-06]
  [2.18026817e-05 4.11751564e-04]
  [4.75140514e-05 7.03595858e-03]
  ...
  [7.18936462e-06 5.57014300e-06]
  [5.54583812e-06 5.44419163e-06]
  [5.25270343e-06 5.13590203e-06]]] and shape: (610, 12, 2)
Masked scores in Binarizer.binarize: [[[2.7500711894390406e-06 2.471496145517449e-06]
  [1.4922506125003565e-05 0.0003563434293027967]
  [3.740171086974442e-05 0.0059176962822675705]
  ...
  [-- --]
  [-- --]
  [-- --]]

 [[2.72162037617818e-06 2.4252890398202e-06]
  [1.4368124539032578e-05 0.0003519526799209416]
  [3.686496347654611e-05 0.00589000666514039]
  ...
  [-- --]
  [-- --]
  [-- --]]

 [[9.020920515467878e-06 8.116666322166566e-06]
  [0.03292933106422424 0.011520754545927048]
  [0.03221007063984871 0.006772112566977739]
  ...
  [-- --]
  [-- --]
  [-- --]]

 ...

 [[8.366770998691209e-06 7.454883871105267e-06]
  [2.8353731977404095e-05 0.0004864160728175193]
  [7.005380030022934e-05 0.0072626350447535515]
  ...
  [-- --]
  [-- --]
  [-- --]]

 [[3.8474790926557034e-05 3.4814078389899805e-05]
  [9.234095341525972e-05 0.0006710421293973923]
  [0.00013634932111017406 0.00696689123287797]
  ...
  [0.01658991351723671 0.0069788238033652306]
  [-- --]
  [-- --]]

 [[5.646941644954495e-06 5.071794475952629e-06]
  [2.180268165830057e-05 0.00041175156366080046]
  [4.7514051402686164e-05 0.007035958580672741]
  ...
  [-- --]
  [-- --]
  [-- --]]] and shape: (610, 12, 2)
self._result: <april.anomalydetection.utils.result.AnomalyDetectionResult object at 0x0000028772D3DEB0>
self._result: <april.anomalydetection.utils.result.AnomalyDetectionResult object at 0x0000028772D3DEB0>
Scores in Binarizer.binarize: None and shape: None
Using result.scores: [[[2.75007119e-06 2.47149615e-06]
  [1.49225061e-05 3.56343429e-04]
  [3.74017109e-05 5.91769628e-03]
  ...
  [3.70947555e-06 2.71421300e-06]
  [2.68737699e-06 2.63530524e-06]
  [2.53050325e-06 2.47446019e-06]]

 [[2.72162038e-06 2.42528904e-06]
  [1.43681245e-05 3.51952680e-04]
  [3.68649635e-05 5.89000667e-03]
  ...
  [3.69087707e-06 2.67805694e-06]
  [2.63525089e-06 2.62548883e-06]
  [2.50425273e-06 2.44820399e-06]]

 [[9.02092052e-06 8.11666632e-06]
  [3.29293311e-02 1.15207545e-02]
  [3.22100706e-02 6.77211257e-03]
  ...
  [1.16274477e-05 8.80699099e-06]
  [8.77520415e-06 8.72896908e-06]
  [8.33869672e-06 8.09178528e-06]]

 ...

 [[8.36677100e-06 7.45488387e-06]
  [2.83537320e-05 4.86416073e-04]
  [7.00538003e-05 7.26263504e-03]
  ...
  [9.99885924e-06 8.13535189e-06]
  [8.30960289e-06 8.19517481e-06]
  [7.53429322e-06 7.87021600e-06]]

 [[3.84747909e-05 3.48140784e-05]
  [9.23409534e-05 6.71042129e-04]
  [1.36349321e-04 6.96689123e-03]
  ...
  [1.65899135e-02 6.97882380e-03]
  [3.70924754e-05 3.76778771e-05]
  [3.55551747e-05 3.52286661e-05]]

 [[5.64694164e-06 5.07179448e-06]
  [2.18026817e-05 4.11751564e-04]
  [4.75140514e-05 7.03595858e-03]
  ...
  [7.18936462e-06 5.57014300e-06]
  [5.54583812e-06 5.44419163e-06]
  [5.25270343e-06 5.13590203e-06]]] and shape: (610, 12, 2)
Masked scores in Binarizer.binarize: [[[2.7500711894390406e-06 2.471496145517449e-06]
  [1.4922506125003565e-05 0.0003563434293027967]
  [3.740171086974442e-05 0.0059176962822675705]
  ...
  [-- --]
  [-- --]
  [-- --]]

 [[2.72162037617818e-06 2.4252890398202e-06]
  [1.4368124539032578e-05 0.0003519526799209416]
  [3.686496347654611e-05 0.00589000666514039]
  ...
  [-- --]
  [-- --]
  [-- --]]

 [[9.020920515467878e-06 8.116666322166566e-06]
  [0.03292933106422424 0.011520754545927048]
  [0.03221007063984871 0.006772112566977739]
  ...
  [-- --]
  [-- --]
  [-- --]]

 ...

 [[8.366770998691209e-06 7.454883871105267e-06]
  [2.8353731977404095e-05 0.0004864160728175193]
  [7.005380030022934e-05 0.0072626350447535515]
  ...
  [-- --]
  [-- --]
  [-- --]]

 [[3.8474790926557034e-05 3.4814078389899805e-05]
  [9.234095341525972e-05 0.0006710421293973923]
  [0.00013634932111017406 0.00696689123287797]
  ...
  [0.01658991351723671 0.0069788238033652306]
  [-- --]
  [-- --]]

 [[5.646941644954495e-06 5.071794475952629e-06]
  [2.180268165830057e-05 0.00041175156366080046]
  [4.7514051402686164e-05 0.007035958580672741]
  ...
  [-- --]
  [-- --]
  [-- --]]] and shape: (610, 12, 2)
self._result: <april.anomalydetection.utils.result.AnomalyDetectionResult object at 0x0000028772D3DEB0>
self._result: <april.anomalydetection.utils.result.AnomalyDetectionResult object at 0x0000028772D3DEB0>
Scores in Binarizer.binarize: None and shape: None
Using result.scores: [[[2.75007119e-06 2.47149615e-06]
  [1.49225061e-05 3.56343429e-04]
  [3.74017109e-05 5.91769628e-03]
  ...
  [3.70947555e-06 2.71421300e-06]
  [2.68737699e-06 2.63530524e-06]
  [2.53050325e-06 2.47446019e-06]]

 [[2.72162038e-06 2.42528904e-06]
  [1.43681245e-05 3.51952680e-04]
  [3.68649635e-05 5.89000667e-03]
  ...
  [3.69087707e-06 2.67805694e-06]
  [2.63525089e-06 2.62548883e-06]
  [2.50425273e-06 2.44820399e-06]]

 [[9.02092052e-06 8.11666632e-06]
  [3.29293311e-02 1.15207545e-02]
  [3.22100706e-02 6.77211257e-03]
  ...
  [1.16274477e-05 8.80699099e-06]
  [8.77520415e-06 8.72896908e-06]
  [8.33869672e-06 8.09178528e-06]]

 ...

 [[8.36677100e-06 7.45488387e-06]
  [2.83537320e-05 4.86416073e-04]
  [7.00538003e-05 7.26263504e-03]
  ...
  [9.99885924e-06 8.13535189e-06]
  [8.30960289e-06 8.19517481e-06]
  [7.53429322e-06 7.87021600e-06]]

 [[3.84747909e-05 3.48140784e-05]
  [9.23409534e-05 6.71042129e-04]
  [1.36349321e-04 6.96689123e-03]
  ...
  [1.65899135e-02 6.97882380e-03]
  [3.70924754e-05 3.76778771e-05]
  [3.55551747e-05 3.52286661e-05]]

 [[5.64694164e-06 5.07179448e-06]
  [2.18026817e-05 4.11751564e-04]
  [4.75140514e-05 7.03595858e-03]
  ...
  [7.18936462e-06 5.57014300e-06]
  [5.54583812e-06 5.44419163e-06]
  [5.25270343e-06 5.13590203e-06]]] and shape: (610, 12, 2)
Masked scores in Binarizer.binarize: [[[2.7500711894390406e-06 2.471496145517449e-06]
  [1.4922506125003565e-05 0.0003563434293027967]
  [3.740171086974442e-05 0.0059176962822675705]
  ...
  [-- --]
  [-- --]
  [-- --]]

 [[2.72162037617818e-06 2.4252890398202e-06]
  [1.4368124539032578e-05 0.0003519526799209416]
  [3.686496347654611e-05 0.00589000666514039]
  ...
  [-- --]
  [-- --]
  [-- --]]

 [[9.020920515467878e-06 8.116666322166566e-06]
  [0.03292933106422424 0.011520754545927048]
  [0.03221007063984871 0.006772112566977739]
  ...
  [-- --]
  [-- --]
  [-- --]]

 ...

 [[8.366770998691209e-06 7.454883871105267e-06]
  [2.8353731977404095e-05 0.0004864160728175193]
  [7.005380030022934e-05 0.0072626350447535515]
  ...
  [-- --]
  [-- --]
  [-- --]]

 [[3.8474790926557034e-05 3.4814078389899805e-05]
  [9.234095341525972e-05 0.0006710421293973923]
  [0.00013634932111017406 0.00696689123287797]
  ...
  [0.01658991351723671 0.0069788238033652306]
  [-- --]
  [-- --]]

 [[5.646941644954495e-06 5.071794475952629e-06]
  [2.180268165830057e-05 0.00041175156366080046]
  [4.7514051402686164e-05 0.007035958580672741]
  ...
  [-- --]
  [-- --]
  [-- --]]] and shape: (610, 12, 2)
self._result: <april.anomalydetection.utils.result.AnomalyDetectionResult object at 0x0000028772D3DEB0>
self._result: <april.anomalydetection.utils.result.AnomalyDetectionResult object at 0x0000028772D3DEB0>
Scores in Binarizer.binarize: None and shape: None
Using result.scores: [[[2.75007119e-06 2.47149615e-06]
  [1.49225061e-05 3.56343429e-04]
  [3.74017109e-05 5.91769628e-03]
  ...
  [3.70947555e-06 2.71421300e-06]
  [2.68737699e-06 2.63530524e-06]
  [2.53050325e-06 2.47446019e-06]]

 [[2.72162038e-06 2.42528904e-06]
  [1.43681245e-05 3.51952680e-04]
  [3.68649635e-05 5.89000667e-03]
  ...
  [3.69087707e-06 2.67805694e-06]
  [2.63525089e-06 2.62548883e-06]
  [2.50425273e-06 2.44820399e-06]]

 [[9.02092052e-06 8.11666632e-06]
  [3.29293311e-02 1.15207545e-02]
  [3.22100706e-02 6.77211257e-03]
  ...
  [1.16274477e-05 8.80699099e-06]
  [8.77520415e-06 8.72896908e-06]
  [8.33869672e-06 8.09178528e-06]]

 ...

 [[8.36677100e-06 7.45488387e-06]
  [2.83537320e-05 4.86416073e-04]
  [7.00538003e-05 7.26263504e-03]
  ...
  [9.99885924e-06 8.13535189e-06]
  [8.30960289e-06 8.19517481e-06]
  [7.53429322e-06 7.87021600e-06]]

 [[3.84747909e-05 3.48140784e-05]
  [9.23409534e-05 6.71042129e-04]
  [1.36349321e-04 6.96689123e-03]
  ...
  [1.65899135e-02 6.97882380e-03]
  [3.70924754e-05 3.76778771e-05]
  [3.55551747e-05 3.52286661e-05]]

 [[5.64694164e-06 5.07179448e-06]
  [2.18026817e-05 4.11751564e-04]
  [4.75140514e-05 7.03595858e-03]
  ...
  [7.18936462e-06 5.57014300e-06]
  [5.54583812e-06 5.44419163e-06]
  [5.25270343e-06 5.13590203e-06]]] and shape: (610, 12, 2)
Masked scores in Binarizer.binarize: [[[2.7500711894390406e-06 2.471496145517449e-06]
  [1.4922506125003565e-05 0.0003563434293027967]
  [3.740171086974442e-05 0.0059176962822675705]
  ...
  [-- --]
  [-- --]
  [-- --]]

 [[2.72162037617818e-06 2.4252890398202e-06]

In [52]:

session = Session(get_engine())
evaluations = session.query(Evaluation).all()
rows = []

for ev in tqdm(evaluations):
    # print(f"Evaluation: {ev}")
    m = ev.model
    # print(f"Model: {m}")
    el = ev.model.training_event_log
    # print(f"Event log: {el}")
    rows.append([m.file_name, m.creation_date, m.hyperparameters, m.training_duration, m.training_host, m.algorithm, 
                 el.name, el.base_name, el.percent_anomalies, el.number,
                 ev.axis, ev.base, ev.heuristic, ev.strategy, ev.label, ev.attribute_name, ev.perspective, ev.precision, ev.recall, ev.f1])
session.close()
columns = ['file_name', 'date', 'hyperparameters', 'training_duration', 'training_host', 'ad',
           'dataset_name', 'process_model', 'noise', 'dataset_id',
           'axis', 'base', 'heuristic', 'strategy', 'label', 'attribute_name', 'perspective', 'precision', 'recall', 'f1']
evaluation = pd.DataFrame(rows, columns=columns)

evaluation.to_pickle(eval_file)

  0%|          | 0/4896 [00:00<?, ?it/s]

In [53]:
synth_datasets = ['paper', 'p2p', 'small', 'medium', 'large', 'huge', 'gigantic', 'wide']
bpic_datasets = ['bpic12', 'bpic13', 'bpic15', 'bpic17']
anonymous_datasets = ['real']
datasets = synth_datasets + bpic_datasets + anonymous_datasets
dataset_types = ['Synthetic', 'Real-life']

orig_ads = [ad['ad'].__name__ for ad in ads if "DAE" in ad['ad'].__name__]
new_ads = [ad['ad'].__name__ for ad in ads if "DAE" not in ad['ad'].__name__]
ads = orig_ads + new_ads

heuristics = [r'$best$', r'$default$', r'$elbow_\downarrow$', r'$elbow_\uparrow$', 
              r'$lp_\leftarrow$', r'$lp_\leftrightarrow$', r'$lp_\rightarrow$']
print(ads)

['WideDAE', 'WideDAE-Leaky-10', 'WideDAE-Leaky-25', 'WideDAE-Leaky-50', 'WideDAE-Leaky-100', 'WideDAE-Leaky-150', 'WideDAE-Leaky-200', 'WideDAE-Leaky-250', 'WideDAE-Leaky-300', 'WideLTNFROZEN-10', 'WideLTNFROZEN-25', 'WideLTNFROZEN-50', 'WideLTNFROZEN-100', 'WideLTNFROZEN-150', 'WideLTNFROZEN-200', 'WideLTNFROZEN-250', 'WideLTNFROZEN-300']

In [54]:
evaluation = evaluation.query(f'ad in {ads} and label == "Anomaly"')

In [55]:
display(evaluation)

,file_name,date,hyperparameters,training_duration,training_host,ad,dataset_name,process_model,noise,dataset_id,axis,base,heuristic,strategy,label,attribute_name,perspective,precision,recall,f1
1,wide-0.3-1_widedae-leaky-100_20250817-183821.4...,2025-08-17 18:38:24.671250,"{'epochs': 6, 'batch_size': 100}",3.228005,Dev-RTX,WideDAE-Leaky-100,wide-0.3-1,wide,0.3,1,0,scores,best,single,Anomaly,name,Control Flow,0.951389,0.878205,0.913333
3,wide-0.3-1_widedae-leaky-100_20250817-183821.4...,2025-08-17 18:38:24.671250,"{'epochs': 6, 'batch_size': 100}",3.228005,Dev-RTX,WideDAE-Leaky-100,wide-0.3-1,wide,0.3,1,0,scores,best,single,Anomaly,user,Data,0.000000,0.000000,0.000000
5,wide-0.3-1_widedae-leaky-100_20250817-183821.4...,2025-08-17 18:38:24.671250,"{'epochs': 6, 'batch_size': 100}",3.228005,Dev-RTX,WideDAE-Leaky-100,wide-0.3-1,wide,0.3,1,1,scores,best,single,Anomaly,name,Control Flow,0.557895,0.507987,0.531773
7,wide-0.3-1_widedae-leaky-100_20250817-183821.4...,2025-08-17 18:38:24.671250,"{'epochs': 6, 'batch_size': 100}",3.228005,Dev-RTX,WideDAE-Leaky-100,wide-0.3-1,wide,0.3,1,1,scores,best,single,Anomaly,user,Data,0.000000,0.000000,0.000000
9,wide-0.3-1_widedae-leaky-100_20250817-183821.4...,2025-08-17 18:38:24.671250,"{'epochs': 6, 'batch_size': 100}",3.228005,Dev-RTX,WideDAE-Leaky-100,wide-0.3-1,wide,0.3,1,2,scores,best,single,Anomaly,name,Control Flow,0.557895,0.507987,0.531773
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4887,wide-0.3-1_wideltnfrozen-50_20250817-183907.95...,2025-08-17 18:39:23.315390,"{'epochs': 6, 'batch_size': 100, 'epochs_ltn': 3}",15.364848,Dev-RTX,WideLTNFROZEN-50,wide-0.3-1,wide,0.3,1,0,scores,stable_right,position_attribute,Anomaly,user,Data,0.250000,0.120690,0.162791
4889,wide-0.3-1_wideltnfrozen-50_20250817-183907.95...,2025-08-17 18:39:23.315390,"{'epochs': 6, 'batch_size': 100, 'epochs_ltn': 3}",15.364848,Dev-RTX,WideLTNFROZEN-50,wide-0.3-1,wide,0.3,1,1,scores,stable_right,position_attribute,Anomaly,name,Control Flow,0.677725,0.456869,0.545802
4891,wide-0.3-1_wideltnfrozen-50_20250817-183907.95...,2025-08-17 18:39:23.315390,"{'epochs': 6, 'batch_size': 100, 'epochs_ltn': 3}",15.364848,Dev-RTX,WideLTNFROZEN-50,wide-0.3-1,wide,0.3,1,1,scores,stable_right,position_attribute,Anomaly,user,Data,0.117647,0.040404,0.060150
4893,wide-0.3-1_wideltnfrozen-50_20250817-183907.95...,2025-08-17 18:39:23.315390,"{'epochs': 6, 'batch_size': 100, 'epochs_ltn': 3}",15.364848,Dev-RTX,WideLTNFROZEN-50,wide-0.3-1,wide,0.3,1,2,scores,stable_right,position_attribute,Anomaly,name,Control Flow,0.677725,0.456869,0.545802
4895,wide-0.3-1_wideltnfrozen-50_20250817-183907.95...,2025-08-17 18:39:23.315390,"{'epochs': 6, 'batch_size': 100, 'epochs_ltn': 3}",15.364848,Dev-RTX,WideLTNFROZEN-50,wide-0.3-1,wide,0.3,1,2,scores,stable_right,position_attribute,Anomaly,user,Data,0.117647,0.040404,0.060150

In [56]:
evaluation['perspective-label'] = evaluation['perspective'] + '-' + evaluation['label']
evaluation['attribute_name-label'] = evaluation['attribute_name'] + '-' + evaluation['label']
evaluation['dataset_type'] = 'Synthetic'
evaluation.loc[evaluation['process_model'].str.contains('bpic'), 'dataset_type'] = 'Real-life'
evaluation.loc[evaluation['process_model'].str.contains('real'), 'dataset_type'] = 'Real-life'

In [57]:
_filtered_evaluation = evaluation.query(f'ad in {ads} and (strategy == "{Strategy.ATTRIBUTE}"'
                                       f' or (strategy == "{Strategy.SINGLE}" and process_model == "bpic12")'
                                       f' or (strategy == "{Strategy.SINGLE}" and ad == "Naive+"))')

In [58]:
filtered_evaluation = _filtered_evaluation.query(f'heuristic == "{Heuristic.DEFAULT}"'
                                                 f' or (heuristic == "{Heuristic.LP_MEAN}" and ad in {orig_ads})'
                                                 f' or (heuristic == "{Heuristic.LP_LEFT}" and ad in {new_ads})'
                                                )

In [59]:
df = filtered_evaluation.query('axis == 0')
df = prettify_dataframe(df)
df = df.groupby(['axis', 'process_model', 'dataset_name', 'ad', 'file_name', 'perspective'])[['precision', 'recall', 'f1']].mean().reset_index()
df = df.groupby(['axis', 'process_model', 'dataset_name', 'ad', 'file_name'])[['precision', 'recall', 'f1']].mean().reset_index()
df['f1'] = 2 * df['recall'] * df['precision'] / (df['recall'] + df['precision'])

df = pd.pivot_table(df, index=['axis', 'ad'], columns=['process_model', 'dataset_name'], values=['precision', 'recall', 'f1'])
df = df.fillna(0)
df = df.stack(1).stack(1).reset_index()
df.to_excel(str(out_dir / 'table.xlsx'), index=False)

# drop rows in column "axis" which have value "Attribute"
df = df.query('axis != "Attribute"')

# df = pd.pivot_table(df, index=['axis', 'ad'], columns=['process_model'], values=['precision', 'recall', 'f1'], aggfunc=np.mean)

df.to_excel(str(excel_file), index=False)
df.to_csv(str(csv_file), index=False)
print(df)

    axis                 ad process_model dataset_name        f1  precision  \
0   Case            WideDAE          Wide   wide-0.3-1  0.537135   0.644068
1   Case   WideDAE-Leaky-10          Wide   wide-0.3-1  0.539032   0.642857
2   Case  WideDAE-Leaky-100          Wide   wide-0.3-1  0.541268   0.649254
3   Case  WideDAE-Leaky-150          Wide   wide-0.3-1  0.535881   0.650794
4   Case  WideDAE-Leaky-200          Wide   wide-0.3-1  0.542857   0.653846
5   Case   WideDAE-Leaky-25          Wide   wide-0.3-1  0.484155   0.625000
6   Case  WideDAE-Leaky-250          Wide   wide-0.3-1  0.539759   0.644928
7   Case  WideDAE-Leaky-300          Wide   wide-0.3-1  0.539759   0.644928
8   Case   WideDAE-Leaky-50          Wide   wide-0.3-1  0.539032   0.642857
9   Case   WideLTNFROZEN-10          Wide   wide-0.3-1  0.351941   0.598039
10  Case  WideLTNFROZEN-100          Wide   wide-0.3-1  0.572110   0.596774
11  Case  WideLTNFROZEN-150          Wide   wide-0.3-1  0.569766   0.538326
12  Case  WideLTNFROZEN-200          Wide   wide-0.3-1  0.390507   0.617284
13  Case   WideLTNFROZEN-25          Wide   wide-0.3-1  0.584955   0.579710
14  Case  WideLTNFROZEN-250          Wide   wide-0.3-1  0.586390   0.560556
15  Case  WideLTNFROZEN-300          Wide   wide-0.3-1  0.590873   0.583252
16  Case   WideLTNFROZEN-50          Wide   wide-0.3-1  0.417853   0.626582

      recall
0   0.460654
1   0.464080
2   0.464080
3   0.455460
4   0.464080
5   0.395115
6   0.464080
7   0.464080
8   0.464080
9   0.249337
10  0.549403
11  0.605106
12  0.285588
13  0.590296
14  0.614721
15  0.598696
16  0.313439

C:\Users\devas\AppData\Local\Temp\ipykernel_9160\661170537.py:9: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df = df.stack(1).stack(1).reset_index()
C:\Users\devas\AppData\Local\Temp\ipykernel_9160\661170537.py:9: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df = df.stack(1).stack(1).reset_index()

In [60]:
display(df)

,axis,ad,process_model,dataset_name,f1,precision,recall
0,Case,WideDAE,Wide,wide-0.3-1,0.537135,0.644068,0.460654
1,Case,WideDAE-Leaky-10,Wide,wide-0.3-1,0.539032,0.642857,0.464080
2,Case,WideDAE-Leaky-100,Wide,wide-0.3-1,0.541268,0.649254,0.464080
3,Case,WideDAE-Leaky-150,Wide,wide-0.3-1,0.535881,0.650794,0.455460
4,Case,WideDAE-Leaky-200,Wide,wide-0.3-1,0.542857,0.653846,0.464080
5,Case,WideDAE-Leaky-25,Wide,wide-0.3-1,0.484155,0.625000,0.395115
6,Case,WideDAE-Leaky-250,Wide,wide-0.3-1,0.539759,0.644928,0.464080
7,Case,WideDAE-Leaky-300,Wide,wide-0.3-1,0.539759,0.644928,0.464080
8,Case,WideDAE-Leaky-50,Wide,wide-0.3-1,0.539032,0.642857,0.464080
9,Case,WideLTNFROZEN-10,Wide,wide-0.3-1,0.351941,0.598039,0.249337
10,Case,WideLTNFROZEN-100,Wide,wide-0.3-1,0.572110,0.596774,0.549403
11,Case,WideLTNFROZEN-150,Wide,wide-0.3-1,0.569766,0.538326,0.605106
12,Case,WideLTNFROZEN-200,Wide,wide-0.3-1,0.390507,0.617284,0.285588
13,Case,WideLTNFROZEN-25,Wide,wide-0.3-1,0.584955,0.579710,0.590296
14,Case,WideLTNFROZEN-250,Wide,wide-0.3-1,0.586390,0.560556,0.614721
15,Case,WideLTNFROZEN-300,Wide,wide-0.3-1,0.590873,0.583252,0.598696
16,Case,WideLTNFROZEN-50,Wide,wide-0.3-1,0.417853,0.626582,0.313439

# End

In [61]:
end_time = arrow.now("Europe/Berlin")
print(f"Start time: {start_time}")
print(f"End time: {end_time}")
print(f"Duration: {end_time - start_time}")

Start time: 2025-08-17T18:38:10.281067+02:00
End time: 2025-08-17T18:42:54.479783+02:00
Duration: 0:04:44.198716