In [1]:
import pandas as pd
import networkx as nx
import numpy as np
from tqdm import tqdm

from april import Dataset
from april.processmining import ProcessMap
from april.fs import get_event_log_files
from april.fs import get_process_model_files

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
GPU found
Memory growth set

# Event Log information

A list of all event logs used in the evaluation

In [2]:
logs = sorted([e.name for e in get_event_log_files() if e.p == 0.3])
columns = ['name', 'base_name', 'num_cases', 'num_events', 'num_activities', 
           'num_attributes', 'attribute_keys', 'attribute_dims', 
           'min_attribute_dim', 'max_attribute_dim',
           'min_case_len', 'max_case_len', 'mean_case_len']
df = []
for log in tqdm(logs):
    d = Dataset(log)
    dim_min = d.attribute_dims[1:].astype(int).min() if d.attribute_dims[1:].size else None
    dim_max = d.attribute_dims[1:].astype(int).max() if d.attribute_dims[1:].size else None
    df.append([log, log.split('-')[0], d.num_cases, d.num_events, d.attribute_dims[0].astype(int), 
               d.num_attributes - 1, d.attribute_keys[1:], d.attribute_dims[1:].astype(int), dim_min, dim_max,
               d.case_lens.min(), d.case_lens.max(), d.case_lens.mean().round(2)])
event_logs = pd.DataFrame(df, columns=columns)

100%|██████████| 16/16 [00:13<00:00,  1.15it/s]

## Basis for Table 1 in the Paper

In [3]:
event_logs

,name,base_name,num_cases,num_events,num_activities,num_attributes,attribute_keys,attribute_dims,min_attribute_dim,max_attribute_dim,min_case_len,max_case_len,mean_case_len
0,medium-0.3-1,medium,5000,41991,65,1,[user],[140],140,140,3,13,8.40
1,medium-0.3-2,medium,5000,39956,65,2,"[day, user]","[13, 140]",13,140,3,13,7.99
2,medium-0.3-3,medium,5000,38990,65,3,"[country, day, user]","[386, 13, 140]",13,386,3,13,7.80
3,medium-0.3-4,medium,5000,39881,65,4,"[company, country, day, user]","[151, 374, 13, 140]",13,374,3,13,7.98
4,p2p-0.3-1,p2p,5000,53193,27,1,[user],[141],141,141,7,16,10.64
5,p2p-0.3-2,p2p,5000,48477,27,2,"[day, user]","[13, 140]",13,140,7,15,9.70
6,p2p-0.3-3,p2p,5000,49957,27,3,"[country, day, user]","[387, 13, 140]",13,387,7,15,9.99
7,p2p-0.3-4,p2p,5000,52211,27,4,"[company, country, day, user]","[148, 353, 13, 141]",13,353,8,16,10.44
8,paper-0.3-1,paper,5000,60536,29,1,[user],[141],141,141,9,17,12.11
9,paper-0.3-2,paper,5000,64792,29,2,"[day, user]","[13, 141]",13,141,9,17,12.96
10,paper-0.3-3,paper,5000,61569,29,3,"[country, day, user]","[381, 13, 141]",13,381,9,17,12.31
11,paper-0.3-4,paper,5000,64982,29,4,"[company, country, day, user]","[146, 341, 13, 140]",13,341,9,17,13.00
12,small-0.3-1,small,5000,53437,41,1,[user],[141],141,141,7,15,10.69
13,small-0.3-2,small,5000,55058,41,2,"[day, user]","[13, 141]",13,141,7,15,11.01
14,small-0.3-3,small,5000,54155,41,3,"[country, day, user]","[380, 13, 141]",13,380,7,15,10.83
15,small-0.3-4,small,5000,56695,41,4,"[company, country, day, user]","[146, 349, 13, 141]",13,349,7,15,11.34

In [4]:
event_logs[['base_name', 'num_activities', 'num_cases', 'num_events', 'min_attribute_dim', 'max_attribute_dim']].groupby('base_name').agg(['count', 'min', 'max'])

          num_activities         num_cases             num_events         \
                   count min max     count   min   max      count    min
base_name
medium                 4  65  65         4  5000  5000          4  38990
p2p                    4  27  27         4  5000  5000          4  48477
paper                  4  29  29         4  5000  5000          4  60536
small                  4  41  41         4  5000  5000          4  53437

                 min_attribute_dim          max_attribute_dim
             max             count min  max             count  min  max
base_name
medium     41991                 4  13  140                 4  140  386
p2p        53193                 4  13  141                 4  140  387
paper      64982                 4  13  141                 4  141  381
small      56695                 4  13  141                 4  141  380

# Process Model Information

In [5]:
maps = sorted([m for m in get_process_model_files()])
df = []
for process_map in tqdm(maps):
    model = ProcessMap.from_plg(process_map)

    num_variants = len(model.variants.cases)
    max_case_len = model.variants.max_case_len

    nodes = model.graph.number_of_nodes()
    edges = model.graph.number_of_edges()
    dens = nx.density(model.graph)
    in_degree = np.mean([d[1] for d in model.graph.in_degree()])
    out_degree = np.mean([d[1] for d in model.graph.out_degree()])

    df.append([nodes, edges, num_variants, max_case_len, dens, in_degree, out_degree])
process_models = pd.DataFrame(df, index=maps, columns=['nodes', 'edges', 'num_variants', 'max_case_len', 'density', 'in_deg', 'out_deg'])

100%|██████████| 8/8 [00:00<00:00, 139.99it/s]

In [6]:
# process_models.loc[['paper', 'p2p', 'small', 'medium', 'large', 'huge', 'gigantic', 'wide', 'testing']].round(2)
process_models.loc[['paper', 'p2p', 'small', 'medium', 'large', 'huge', 'gigantic', 'wide']].round(2)

          nodes  edges  num_variants  max_case_len  density  in_deg  out_deg
paper        16     18             8            12     0.08    1.12     1.12
p2p          15     18             8            11     0.09    1.20     1.20
small        22     26             6            10     0.06    1.18     1.18
medium       34     48            25             8     0.04    1.41     1.41
large        44     56            28            12     0.03    1.27     1.27
huge         56     75            39            11     0.02    1.34     1.34
gigantic     80    119            71            11     0.02    1.49     1.49
wide         36     53            19             7     0.04    1.47     1.47